# Generated by Django 4.0.3 on 2022-08-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=20)),
                ('TotalSamples', models.IntegerField()),
                ('Negative', models.IntegerField()),
                ('Positive', models.IntegerField()),
            ],
        ),
    ]
